2019-12-15T02:54:51.925818+00:00 app[web.1]: [2019-12-15 02:54:51 +0000] [10] [INFO] Booting worker with pid: 10
2019-12-15T02:54:52.012958+00:00 app[web.1]: [2019-12-15 02:54:52 +0000] [11] [INFO] Booting worker with pid: 11
2019-12-15T02:54:52.361674+00:00 app[web.1]: [2019-12-15 02:54:52 +0000] [10] [ERROR] Exception in worker process
2019-12-15T02:54:52.361700+00:00 app[web.1]: Traceback (most recent call last):
2019-12-15T02:54:52.361704+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-12-15T02:54:52.361713+00:00 app[web.1]: worker.init_process()
2019-12-15T02:54:52.361716+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
2019-12-15T02:54:52.361718+00:00 app[web.1]: self.load_wsgi()
2019-12-15T02:54:52.361721+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2019-12-15T02:54:52.361723+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-12-15T02:54:52.361726+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-12-15T02:54:52.361728+00:00 app[web.1]: self.callable = self.load()
2019-12-15T02:54:52.361730+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2019-12-15T02:54:52.361732+00:00 app[web.1]: return self.load_wsgiapp()
2019-12-15T02:54:52.361734+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2019-12-15T02:54:52.361736+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-12-15T02:54:52.361739+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
2019-12-15T02:54:52.361741+00:00 app[web.1]: mod = importlib.import_module(module)
2019-12-15T02:54:52.361743+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
2019-12-15T02:54:52.361748+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2019-12-15T02:54:52.361751+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2019-12-15T02:54:52.361753+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2019-12-15T02:54:52.361755+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2019-12-15T02:54:52.361757+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2019-12-15T02:54:52.361760+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2019-12-15T02:54:52.361762+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-12-15T02:54:52.361764+00:00 app[web.1]: File "/app/microblog/wsgi.py", line 13, in <module>
2019-12-15T02:54:52.361767+00:00 app[web.1]: from whitenoise.django import DjangoWhiteNoise
2019-12-15T02:54:52.361769+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/whitenoise/django.py", line 18, in <module>
2019-12-15T02:54:52.361771+00:00 app[web.1]: from django.utils.six.moves.urllib.parse import urlparse
2019-12-15T02:54:52.361774+00:00 app[web.1]: ModuleNotFoundError: No module named 'django.utils.six'
2019-12-15T02:54:52.361776+00:00 app[web.1]: [2019-12-15 02:54:52 +0000] [10] [INFO] Worker exiting (pid: 10)
2019-12-15T02:54:52.554147+00:00 app[web.1]: [2019-12-15 02:54:52 +0000] [11] [ERROR] Exception in worker process
2019-12-15T02:54:52.554152+00:00 app[web.1]: Traceback (most recent call last):
2019-12-15T02:54:52.554155+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2019-12-15T02:54:52.554158+00:00 app[web.1]: worker.init_process()
2019-12-15T02:54:52.554160+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
2019-12-15T02:54:52.554163+00:00 app[web.1]: self.load_wsgi()
2019-12-15T02:54:52.554165+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2019-12-15T02:54:52.554167+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2019-12-15T02:54:52.554170+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2019-12-15T02:54:52.554172+00:00 app[web.1]: self.callable = self.load()
2019-12-15T02:54:52.554174+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2019-12-15T02:54:52.554176+00:00 app[web.1]: return self.load_wsgiapp()
2019-12-15T02:54:52.554179+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2019-12-15T02:54:52.554181+00:00 app[web.1]: return util.import_app(self.app_uri)
2019-12-15T02:54:52.554183+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
2019-12-15T02:54:52.554185+00:00 app[web.1]: mod = importlib.import_module(module)
2019-12-15T02:54:52.554187+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
2019-12-15T02:54:52.554190+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2019-12-15T02:54:52.554192+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2019-12-15T02:54:52.554194+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2019-12-15T02:54:52.554196+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2019-12-15T02:54:52.554198+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2019-12-15T02:54:52.554201+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2019-12-15T02:54:52.554203+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-12-15T02:54:52.554205+00:00 app[web.1]: File "/app/microblog/wsgi.py", line 13, in <module>
2019-12-15T02:54:52.554207+00:00 app[web.1]: from whitenoise.django import DjangoWhiteNoise
2019-12-15T02:54:52.554209+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/whitenoise/django.py", line 18, in <module>
2019-12-15T02:54:52.554214+00:00 app[web.1]: from django.utils.six.moves.urllib.parse import urlparse
2019-12-15T02:54:52.554217+00:00 app[web.1]: ModuleNotFoundError: No module named 'django.utils.six'
2019-12-15T02:54:52.554436+00:00 app[web.1]: [2019-12-15 02:54:52 +0000] [11] [INFO] Worker exiting (pid: 11)
2019-12-15T02:54:52.766109+00:00 heroku[web.1]: State changed from up to crashed
2019-12-15T02:54:52.643674+00:00 app[web.1]: Traceback (most recent call last):
2019-12-15T02:54:52.643697+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
2019-12-15T02:54:52.644130+00:00 app[web.1]: self.sleep()
2019-12-15T02:54:52.644169+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
2019-12-15T02:54:52.644709+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2019-12-15T02:54:52.644745+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2019-12-15T02:54:52.645204+00:00 app[web.1]: self.reap_workers()
2019-12-15T02:54:52.645534+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2019-12-15T02:54:52.646602+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2019-12-15T02:54:52.646998+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2019-12-15T02:54:52.647062+00:00 app[web.1]: 
2019-12-15T02:54:52.647065+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-12-15T02:54:52.647067+00:00 app[web.1]: 
2019-12-15T02:54:52.647105+00:00 app[web.1]: Traceback (most recent call last):
2019-12-15T02:54:52.647144+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
2019-12-15T02:54:52.647687+00:00 app[web.1]: sys.exit(run())
2019-12-15T02:54:52.647724+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
2019-12-15T02:54:52.648486+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2019-12-15T02:54:52.648528+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
2019-12-15T02:54:52.650706+00:00 app[web.1]: super().run()
2019-12-15T02:54:52.650741+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
2019-12-15T02:54:52.651106+00:00 app[web.1]: Arbiter(self).run()
2019-12-15T02:54:52.651144+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
2019-12-15T02:54:52.651590+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2019-12-15T02:54:52.651626+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
2019-12-15T02:54:52.652140+00:00 app[web.1]: self.stop()
2019-12-15T02:54:52.652176+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
2019-12-15T02:54:52.652715+00:00 app[web.1]: time.sleep(0.1)
2019-12-15T02:54:52.652754+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2019-12-15T02:54:52.653191+00:00 app[web.1]: self.reap_workers()
2019-12-15T02:54:52.653228+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2019-12-15T02:54:52.653870+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2019-12-15T02:54:52.654093+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2019-12-15T02:54:52.749323+00:00 heroku[web.1]: Process exited with status 1
2019-12-15T02:54:54.000000+00:00 app[api]: Build succeeded
2019-12-15T02:55:09.165107+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=microblog-django-study.herokuapp.com request_id=6e09bca3-38d2-449f-8d0f-af4d0863d016 fwd="118.241.27.135" dyno= connect= service= status=503 bytes= protocol=https
2019-12-15T02:55:09.820299+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=microblog-django-study.herokuapp.com request_id=156032b4-6af9-4a7a-9146-4f9a95b56954 fwd="118.241.27.135" dyno= connect= service= status=503 bytes= protocol=https
(microblog) mbps:microblog $ 
